# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            My Blog
tagline:          'TAGLINE'
description:      'Blog info. '
url:              http://y30308.github.io/
baseurl:          

author:
  name:           'Jyn'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          2.1.0

github:						
  repo:           https://github.com/poole/hyde

